[package]
name = "japi"
version = "0.1.0"
authors = ["Naimor <romain.bellande@orange.fr>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"
