version: '3'

services:
  postgres:
    build: './docker/postgres'
    env_file:
      - .env
    environment:
      HOSTNAME: 'postgres'
    volumes:
    - './pgdata:/var/lib/postgresql/data'
    ports:
    - $POSTGRES_PORT:5432
